
# Continuous Integration
name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

    # ================================
    # CHECKOUT
    # ================================
    - name: Checkout git branch
      uses: actions/checkout@v3
      with:
        # Fetch all history for all tags and branches (recommended by SonarQube)
        fetch-depth: 0

    # ================================
    # SET UP JDK
    # ================================
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-package: jdk
        java-version: 11

    # ================================
    # CACHE SONARCLOUD PACKAGES
    # ================================
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-sonar
        path: |
          ~/.sonar/cache
        restore-keys: |
          ${{ runner.os }}-sonar

    # ================================
    # SETUP GRADLE
    # ================================
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

    # ================================
    # BUILD
    # ================================
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build -x check --info --scan

    # ================================
    # CHECK
    # ================================
    - name: Check
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check --info --scan

    # ================================
    # ANALYZE
    # ================================
    - name: Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_ORGANIZATION: guillermocalvo
      uses: gradle/gradle-build-action@v2
      with:
        arguments: sonarqube --info --scan
