
# Continuous Integration
name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

    # ================================
    # CHECKOUT
    # ================================
    - name: Checkout git branch
      uses: actions/checkout@v4
      with:
        # Fetch all history for all tags and branches (recommended by SonarQube)
        fetch-depth: 0

    # ================================
    # SET UP JDK
    # ================================
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-package: jdk
        java-version: 17

    # ================================
    # CACHE SONARCLOUD PACKAGES
    # ================================
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-sonar
        path: |
          ~/.sonar/cache
        restore-keys: |
          ${{ runner.os }}-sonar

    # ================================
    # SETUP GRADLE
    # ================================
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"
        cache-read-only: ${{ github.ref_name != 'main' && github.ref_name != 'develop' }}

    # ================================
    # BUILD
    # ================================
    - name: Build
      run: ./gradlew build -x check

    # ================================
    # CHECK
    # ================================
    - name: Check
      run: ./gradlew check

    # ================================
    # ANALYZE
    # ================================
    - name: Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_ORGANIZATION: guillermocalvo
      run: ./gradlew sonar
