
# Publish a new Release
name: Release

on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+*']

jobs:
  build:

    name: Publish
    runs-on: ubuntu-latest

    steps:

    # ================================
    # CHECKOUT
    # ================================
    - name: Checkout git tag
      uses: actions/checkout@v3

    # ================================
    # SET UP JDK
    # ================================
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-package: jdk
        java-version: 11

    # ================================
    # PUBLISH
    # ================================
    - name: Publish
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publishPlugins --info --scan
